/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ns_thesis_wordindex_NativeWordIndex */

#ifndef _Included_org_ns_thesis_wordindex_NativeWordIndex
#define _Included_org_ns_thesis_wordindex_NativeWordIndex
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ns_thesis_wordindex_NativeWordIndex_TERM_BUFFER_MARK
#define org_ns_thesis_wordindex_NativeWordIndex_TERM_BUFFER_MARK 0L
#undef org_ns_thesis_wordindex_NativeWordIndex_MIN_QUERY_BUFFER_SIZE
#define org_ns_thesis_wordindex_NativeWordIndex_MIN_QUERY_BUFFER_SIZE 512L
#undef org_ns_thesis_wordindex_NativeWordIndex_MIN_INDEXING_BUFFER_SIZE
#define org_ns_thesis_wordindex_NativeWordIndex_MIN_INDEXING_BUFFER_SIZE 4096L
#undef org_ns_thesis_wordindex_NativeWordIndex_MIN_WORD_CAPACITY_ESTIMATE
#define org_ns_thesis_wordindex_NativeWordIndex_MIN_WORD_CAPACITY_ESTIMATE 64L
#undef org_ns_thesis_wordindex_NativeWordIndex_NULL
#define org_ns_thesis_wordindex_NativeWordIndex_NULL 0LL
/*
 * Class:     org_ns_thesis_wordindex_NativeWordIndex
 * Method:    wordIndexOpen
 * Signature: (Ljava/lang/String;JJZ)J
 */
JNIEXPORT jlong JNICALL Java_org_ns_thesis_wordindex_NativeWordIndex_wordIndexOpen(
    JNIEnv *, jclass, jstring, jlong, jlong, jboolean);

/*
 * Class:     org_ns_thesis_wordindex_NativeWordIndex
 * Method:    wordIndexClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_org_ns_thesis_wordindex_NativeWordIndex_wordIndexClose(JNIEnv *, jclass, jlong);

/*
 * Class:     org_ns_thesis_wordindex_NativeWordIndex
 * Method:    wordIndexReadWithContextBuffered
 * Signature: (JLjava/nio/ByteBuffer;JLjava/lang/String;IIJ)J
 */
JNIEXPORT jlong JNICALL
Java_org_ns_thesis_wordindex_NativeWordIndex_wordIndexReadWithContextBuffered(
    JNIEnv *, jclass, jlong, jobject, jlong, jstring, jint, jint, jlong);

/*
 * Class:     org_ns_thesis_wordindex_NativeWordIndex
 * Method:    wordIndexCloseIterator
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_org_ns_thesis_wordindex_NativeWordIndex_wordIndexCloseIterator(JNIEnv *, jclass,
                                                                    jlong);

#ifdef __cplusplus
}
#endif
#endif
